# Generated by Django 5.1.7 on 2025-04-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frequencias", "0001_initial"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frequencia",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="turmas.turma"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="frequencia",
            unique_together={("aluno", "turma", "data")},
        ),
    ]
