# Generated by Django 5.1.7 on 2025-04-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0003_alter_frequencia_options_and_more'),
        ('frequencias', 'xxxx_update_aluno_fk'),
    ]

    operations = [
    ]
