# Generated by Django 5.2.2 on 2025-09-13 15:54

from django.db import migrations


def migrar_dados_presenca(apps, schema_editor):
    """
    Migra dados do modelo antigo presencas.Presenca para o novo presencas.RegistroPresenca.
    """
    try:
        # Obter os modelos do estado histórico do aplicativo
        Presenca = apps.get_model("presencas", "Presenca")
        RegistroPresenca = apps.get_model("presencas", "RegistroPresenca")

        registros_a_criar = []

        # Usar um set para rastrear registros únicos já processados
        registros_unicos = set()

        for presenca in Presenca.objects.all().iterator():
            # Chave de unicidade para o novo modelo
            chave_unica = (
                presenca.aluno_id,
                presenca.turma_id,
                presenca.atividade_id,
                presenca.data,
            )

            if chave_unica in registros_unicos:
                continue  # Pula registros duplicados do modelo antigo

            registros_unicos.add(chave_unica)

            registros_a_criar.append(
                RegistroPresenca(
                    aluno_id=presenca.aluno_id,
                    turma_id=presenca.turma_id,
                    atividade_id=presenca.atividade_id,
                    data=presenca.data,
                    status="P" if presenca.presente else "F",
                    justificativa=presenca.justificativa,
                    convocado=True,  # O campo 'convocado' não existe no modelo antigo, assume-se True
                    registrado_por=presenca.registrado_por,
                    data_registro=presenca.data_registro,
                )
            )

        # Criar todos os registros de uma vez para melhor performance
        RegistroPresenca.objects.bulk_create(registros_a_criar, ignore_conflicts=True)

    except LookupError:
        # Se os modelos antigos não existirem (ex: em uma nova instalação), não faz nada.
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("presencas", "0002_alter_configuracaopresenca_unique_together_and_more"),
        ("alunos", "0002_alter_aluno_celular_primeiro_contato_and_more"),
    ]

    operations = [
        migrations.RunPython(migrar_dados_presenca, migrations.RunPython.noop),
    ]
