# Generated by Django 5.2.2 on 2025-09-13 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="celular_primeiro_contato",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Número de celular inválido", regex="^\\\\d{10,11}$"
                    )
                ],
                verbose_name="Celular do 1º Contato",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="celular_segundo_contato",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Número de celular inválido", regex="^\\\\d{10,11}$"
                    )
                ],
                verbose_name="Celular do 2º Contato",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                db_index=True,
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF deve conter 11 dígitos numéricos",
                        regex="^\\\\d{11}$",
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="numero_iniciatico",
            field=models.CharField(
                default="TEMP",
                help_text="Número único de identificação iniciática",
                max_length=20,
                verbose_name="Número Iniciático",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("a", "Ativo"),
                    ("d", "Desligado"),
                    ("f", "Falecido"),
                    ("e", "Excluído"),
                ],
                default="a",
                max_length=1,
                verbose_name="Situação do Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="situacao_iniciatica",
            field=models.CharField(
                choices=[
                    ("a", "Ativo"),
                    ("d", "Desligado"),
                    ("f", "Falecido"),
                    ("e", "Excluído"),
                ],
                default="a",
                max_length=20,
                verbose_name="Situação Iniciática",
            ),
        ),
    ]
