# Generated by Django 5.2.2 on 2025-07-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorico',
            name='nome_iniciatico',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Nome Iniciático'
            ),
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='numero_iniciatico',
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name='Número Iniciático'
            ),
        ),
    ]
