# Generated by Django 5.2.4 on 2025-07-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Cidade"),
                ),
                (
                    "codigo_ibge",
                    models.CharField(
                        blank=True,
                        help_text="Código IBGE da cidade",
                        max_length=7,
                        null=True,
                        unique=True,
                        verbose_name="Código IBGE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="aluno",
            options={
                "ordering": ["nome"],
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="nacionalidade",
            field=models.CharField(
                blank=True,
                default="Brasileira",
                help_text="Campo de texto livre - será substituído pelo campo País de Nacionalidade",
                max_length=50,
                null=True,
                verbose_name="Nacionalidade (Texto)",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="naturalidade",
            field=models.CharField(
                blank=True,
                help_text="Campo de texto livre - será substituído pelo campo Cidade de Naturalidade",
                max_length=50,
                null=True,
                verbose_name="Naturalidade (Texto)",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="cidade_naturalidade",
            field=models.ForeignKey(
                blank=True,
                help_text="Cidade onde o aluno nasceu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="naturais",
                to="alunos.cidade",
                verbose_name="Cidade de Naturalidade",
            ),
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Sigla do estado (ex: SP, RJ, MG)",
                        max_length=2,
                        unique=True,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Estado"
                    ),
                ),
                (
                    "regiao",
                    models.CharField(
                        choices=[
                            ("Norte", "Norte"),
                            ("Nordeste", "Nordeste"),
                            ("Centro-Oeste", "Centro-Oeste"),
                            ("Sudeste", "Sudeste"),
                            ("Sul", "Sul"),
                        ],
                        max_length=20,
                        verbose_name="Região",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["nome"], name="alunos_esta_nome_2eed62_idx"),
                    models.Index(
                        fields=["codigo"], name="alunos_esta_codigo_c7eaf3_idx"
                    ),
                    models.Index(
                        fields=["regiao"], name="alunos_esta_regiao_ad46fa_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="cidade",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cidades",
                to="alunos.estado",
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código ISO do país (ex: BRA, ARG, USA)",
                        max_length=3,
                        unique=True,
                        verbose_name="Código ISO",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do País"
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        help_text="Gentílico (ex: brasileiro, argentino, americano)",
                        max_length=100,
                        verbose_name="Nacionalidade",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["nome"], name="alunos_pais_nome_adb5e1_idx"),
                    models.Index(
                        fields=["nacionalidade"], name="alunos_pais_naciona_95a98f_idx"
                    ),
                    models.Index(fields=["ativo"], name="alunos_pais_ativo_1bfd69_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="aluno",
            name="pais_nacionalidade",
            field=models.ForeignKey(
                blank=True,
                help_text="País que define a nacionalidade do aluno",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nacionais",
                to="alunos.pais",
                verbose_name="País de Nacionalidade",
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(fields=["email"], name="alunos_alun_email_9690b2_idx"),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["numero_iniciatico"], name="alunos_alun_numero__412a09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["situacao"], name="alunos_alun_situaca_d6babc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(fields=["ativo"], name="alunos_alun_ativo_26ee3e_idx"),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["pais_nacionalidade"], name="alunos_alun_pais_na_408f04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(
                fields=["cidade_naturalidade"], name="alunos_alun_cidade__0313e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aluno",
            index=models.Index(fields=["nome"], name="alunos_alun_nome_6c76a2_idx"),
        ),
        migrations.AddIndex(
            model_name="cidade",
            index=models.Index(fields=["nome"], name="alunos_cida_nome_f4fc7f_idx"),
        ),
        migrations.AddIndex(
            model_name="cidade",
            index=models.Index(
                fields=["estado"], name="alunos_cida_estado__88a3c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cidade",
            index=models.Index(
                fields=["codigo_ibge"], name="alunos_cida_codigo__39b0aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cidade",
            unique_together={("nome", "estado")},
        ),
    ]
