# Generated by Django 5.2.2 on 2025-09-13 15:55

from django.db import migrations


def gerar_numeros_iniciaticos_unicos(apps, schema_editor):
    """Gera números iniciáticos únicos para alunos com o valor temporário 'TEMP'."""
    Aluno = apps.get_model("alunos", "Aluno")
    for aluno in Aluno.objects.filter(numero_iniciatico="TEMP"):
        aluno.numero_iniciatico = f"TEMP-{aluno.id}"
        aluno.save(update_fields=["numero_iniciatico"])


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_alter_aluno_celular_primeiro_contato_and_more"),
    ]

    operations = [
        migrations.RunPython(
            gerar_numeros_iniciaticos_unicos, migrations.RunPython.noop
        ),
    ]
