# Generated by Django 5.2.4 on 2025-07-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_registrohistorico_nome_iniciatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_iniciatico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Iniciático'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_iniciatico',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Número Iniciático'),
        ),
    ]
