# Generated by Django 5.2.2 on 2025-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0003_auto_20250913_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="numero_iniciatico",
            field=models.CharField(
                help_text="Número único de identificação iniciática",
                max_length=20,
                unique=True,
                verbose_name="Número Iniciático",
            ),
        ),
    ]
