# Generated by Django 5.1.7 on 2025-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0004_remove_data_iniciacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="situacao_iniciatica",
            field=models.CharField(
                choices=[
                    ("ATIVO", "Ativo"),
                    ("AFASTADO", "Afastado"),
                    ("ESPECIAIS", "Especiais"),
                    ("EXCLUIDO", "Excluído"),
                    ("FALECIDO", "Falecido"),
                    ("LOI", "LOI"),
                ],
                default="ATIVO",
                max_length=20,
                verbose_name="Situação Iniciática",
            ),
        ),
    ]
