# Generated by Django 5.2.5 on 2025-10-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_numero_iniciatico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohistorico',
            name='nome_iniciatico',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='numero_iniciatico',
        ),
    ]
