# Generated by GitHub Copilot on 2025-11-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0005_remove_registrohistorico_nome_iniciatico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codigo",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="tipocodigo",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
