# Generated by Django 5.2.5 on 2025-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0005_remove_registrohistorico_nome_iniciatico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalidadeFaltante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        help_text="Chave única da requisição (ex: estado:RJ ou cep:23560352)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("provedor", models.CharField(blank=True, max_length=50, null=True)),
                ("parametros", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tentativas", models.IntegerField(default=0)),
                ("resultado_cache", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Localidade Faltante",
                "verbose_name_plural": "Localidades Faltantes",
                "indexes": [
                    models.Index(
                        fields=["status"], name="alunos_loca_status_fdc9c1_idx"
                    )
                ],
            },
        ),
    ]
