# Generated by Django 5.2.8 on 2025-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_altera_max_length_cpf_aceita_mascara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(db_index=True, help_text='Digite apenas números ou com máscara (999.999.999-99)', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
