# Generated by Django 5.2.5 on 2025-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0008_ajusta_max_length_cep_celulares_mascara"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="celular_primeiro_contato",
            field=models.CharField(
                blank=True,
                help_text="Digite apenas números ou com máscara (99) 99999-9999",
                max_length=15,
                null=True,
                verbose_name="Celular do 1º Contato",
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="celular_segundo_contato",
            field=models.CharField(
                blank=True,
                help_text="Digite apenas números ou com máscara (99) 99999-9999",
                max_length=15,
                null=True,
                verbose_name="Celular do 2º Contato",
            ),
        ),
    ]
