# Generated by Django 5.2.5 on 2025-12-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0009_alter_aluno_celular_primeiro_contato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Digite apenas números ou com máscara (99) 9999-9999",
                max_length=15,
                null=True,
                verbose_name="Telefone",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="celular",
            field=models.CharField(
                blank=True,
                help_text="Digite apenas números ou com máscara (99) 99999-9999",
                max_length=15,
                null=True,
                verbose_name="Celular",
            ),
        ),
    ]
