# Generated by Django 5.2.9 on 2025-12-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_aluno_telefone_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('sem_instrucao', 'Sem instrução (ou Nenhuma)'), ('fundamental_incompleto', 'Fundamental - Incompleto'), ('fundamental_completo', 'Fundamental - Completo'), ('medio_incompleto', 'Médio - Incompleto'), ('medio_completo', 'Médio - Completo'), ('superior_incompleto', 'Superior - Incompleto'), ('superior_completo', 'Superior - Completo'), ('pos_especializacao_incompleto', 'Pós-graduação (Especialização/MBA) - Incompleto'), ('pos_especializacao_completo', 'Pós-graduação (Especialização/MBA) - Completo'), ('mestrado_incompleto', 'Mestrado - Incompleto'), ('mestrado_completo', 'Mestrado - Completo'), ('doutorado_incompleto', 'Doutorado - Incompleto'), ('doutorado_completo', 'Doutorado - Completo')], max_length=50, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('separado', 'Separado(a) judicialmente')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
    ]
