# Generated by Django 5.2.9 on 2025-12-13 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_aluno_escolaridade_alter_aluno_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado_ref',
            field=models.ForeignKey(blank=True, help_text='Estado do endereço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_estado', to='alunos.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='bairro_ref',
            field=models.ForeignKey(blank=True, help_text='Bairro do endereço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_bairro', to='alunos.bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cidade_ref',
            field=models.ForeignKey(blank=True, help_text='Cidade do endereço', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_cidade', to='alunos.cidade', verbose_name='Cidade'),
        ),
    ]
