# Generated by Django 5.2.9 on 2025-12-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_aluno_estado_ref_alter_aluno_bairro_ref_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aluno',
            name='alunos_alun_ativo_26ee3e_idx',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
    ]
