# Generated by Django 5.2.9 on 2025-12-23 00:39

import alunos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_remove_ativo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=alunos.models._upload_foto_path, verbose_name='Foto'),
        ),
    ]
