# Generated by Django 5.2.5 on 2025-09-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_remove_aluno_fator_rh_alter_aluno_tipo_sanguineo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='naturalidade',
        ),
    ]
