# Generated by Django 5.1.7 on 2025-04-01 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "codigo_curso",
                    models.IntegerField(
                        help_text="Digite um número inteiro positivo",
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Código do Curso",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Curso"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Descrição"),
                ),
                (
                    "duracao",
                    models.PositiveIntegerField(
                        default=6, verbose_name="Duração (meses)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["codigo_curso"],
            },
        ),
    ]
