# Generated by Django 5.1.7 on 2025-05-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('PAGO', 'Pago'),
                    ('ATRASADO', 'Atrasado'),
                    ('CANCELADO', 'Cancelado'),
                ],
                default='PENDENTE',
                max_length=10,
            ),
        ),
    ]
