# Generated by Django 5.1.7 on 2025-05-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_pagamento_valor_pago_alter_pagamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='comprovante',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='numero_parcela',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='total_parcelas',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
