# Generated by Django 5.1.7 on 2025-05-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_remove_pagamento_comprovante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DINHEIRO', 'Dinheiro'),
                    ('CARTAO_CREDITO', 'Cartão de Crédito'),
                    ('CARTAO_DEBITO', 'Cartão de Débito'),
                    ('BOLETO', 'Boleto Bancário'),
                    ('TRANSFERENCIA', 'Transferência'),
                    ('PIX', 'PIX'),
                    ('OUTRO', 'Outro'),
                ],
                max_length=20,
                null=True,
                verbose_name='Método de Pagamento',
            ),
        ),
    ]
