# Generated by Django 5.1.7 on 2025-05-19 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('pagamentos', '0004_pagamento_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='alunos.aluno',
                verbose_name='Aluno',
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data de Pagamento'
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DINHEIRO', 'Dinheiro'),
                    ('PIX', 'PIX'),
                    ('CARTAO_CREDITO', 'Cartão de Crédito'),
                    ('CARTAO_DEBITO', 'Cartão de Débito'),
                    ('TRANSFERENCIA', 'Transferência Bancária'),
                    ('BOLETO', 'Boleto'),
                    ('OUTRO', 'Outro'),
                ],
                max_length=20,
                null=True,
                verbose_name='Método de Pagamento',
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('PAGO', 'Pago'),
                    ('ATRASADO', 'Atrasado'),
                    ('CANCELADO', 'Cancelado'),
                ],
                default='PENDENTE',
                max_length=10,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name='Valor'
            ),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Valor Pago',
            ),
        ),
    ]
