[tool.black]
skip-string-normalization = true
line-length = 88
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | alunos/views.py  # Adicione os arquivos específicos que você quer excluir
)/
'''