# Generated by Django 5.1.7 on 2025-04-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa'), ('C', 'Concluída')], default='A', max_length=1, verbose_name='Status')),
                ('capacidade', models.PositiveIntegerField(default=30, verbose_name='Capacidade de Alunos')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True, verbose_name='Data da Matrícula')),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('C', 'Cancelada'), ('F', 'Finalizada')], default='A', max_length=1, verbose_name='Status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
