# Generated by Django 5.1.7 on 2025-04-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_remove_aluno_id_alter_aluno_cpf"),
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={
                "ordering": ["-data_matricula"],
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
            },
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="status",
        ),
        migrations.AddField(
            model_name="matricula",
            name="ativa",
            field=models.BooleanField(
                default=True, verbose_name="Matrícula Ativa"
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alunos.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="data_matricula",
            field=models.DateField(verbose_name="Data da Matrícula"),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="turmas.turma",
                verbose_name="Turma",
            ),
        ),
    ]
