# Generated by Django 5.1.7 on 2025-05-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('matriculas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pendente', 'Pendente'),
                            ('pago', 'Pago'),
                            ('cancelado', 'Cancelado'),
                        ],
                        default='pendente',
                        max_length=20,
                    ),
                ),
                (
                    'metodo_pagamento',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('pix', 'PIX'),
                            ('cartao_credito', 'Cartão de Crédito'),
                            ('cartao_debito', 'Cartão de Débito'),
                            ('boleto', 'Boleto Bancário'),
                            ('dinheiro', 'Dinheiro'),
                            ('transferencia', 'Transferência Bancária'),
                            ('outro', 'Outro'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'comprovante',
                    models.FileField(
                        blank=True, null=True, upload_to='pagamentos/comprovantes/'
                    ),
                ),
                ('numero_parcela', models.PositiveIntegerField(blank=True, null=True)),
                ('total_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pagamentos',
                        to='alunos.aluno',
                    ),
                ),
                (
                    'matricula',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='pagamentos',
                        to='matriculas.matricula',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
