# Generated by Django 5.1.7 on 2025-05-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAdministrativo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'codigo_cargo',
                    models.CharField(
                        max_length=10, unique=True, verbose_name='Código do Cargo'
                    ),
                ),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                (
                    'descricao',
                    models.TextField(blank=True, null=True, verbose_name='Descrição'),
                ),
            ],
            options={
                'verbose_name': 'Cargo Administrativo',
                'verbose_name_plural': 'Cargos Administrativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoCargo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='atribuicoes_cargo',
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
                (
                    'cargo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='cargos.cargoadministrativo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Atribuição de Cargo',
                'verbose_name_plural': 'Atribuições de Cargos',
            },
        ),
    ]
