# Generated by Django 5.1.7 on 2025-04-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
        ("cargos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtribuicaoCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alunos.aluno"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cargos.cargoadministrativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Cargo",
                "verbose_name_plural": "Atribuições de Cargos",
            },
        ),
    ]
