# Generated by Django 5.1.7 on 2025-04-18 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0002_atribuicaocargo"),
        (
            "turmas",
            "0006_turma_alerta_instrutor_turma_alerta_mensagem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="atribuicaocargo",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atribuicoes_cargo",
                to="turmas.turma",
                verbose_name="Turma",
            ),
        ),
    ]
