# Generated by Django 5.1.7 on 2025-05-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
