# Generated by Django 5.2.2 on 2025-06-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={
                'ordering': ['nome'],
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.IntegerField(
                blank=True,
                help_text='Digite um número inteiro positivo',
                null=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Código do Curso',
            ),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
