# Generated by Django 5.1.7 on 2025-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_codigo_curso_remove_curso_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (meses)'),
        ),
    ]
