# Generated by Django 5.1.7 on 2025-03-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('data_iniciacao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciacoes', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Iniciação',
                'verbose_name_plural': 'Iniciações',
                'ordering': ['-data_iniciacao'],
            },
        ),
    ]
