# docker/Dockerfile.nginx
FROM nginx:alpine

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/static /var/www/media

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
