from django.core.management.base import BaseCommand
from alunos.models import Aluno
from cursos.models import Curso
from datetime import date, time


class Command(BaseCommand):
    help = "Popula o banco de dados com alunos para testes"

    def handle(self, *args, **kwargs):
        # Verificar se existem cursos
        if Curso.objects.count() == 0:
            self.stdout.write(
                self.style.WARNING(
                    "Nenhum curso encontrado. Execute primeiro o comando popular_cursos."
                )
            )
            return

        # Dados dos alunos para teste
        alunos_dados = [
            {
                "cpf": "12345678901",
                "nome": "João Silva",
                "data_nascimento": date(1990, 5, 15),
                "hora_nascimento": time(8, 30),
                "email": "joao.silva@exemplo.com",
                "sexo": "M",
                "numero_iniciatico": "101A",
                "nome_iniciatico": "Ananda",
                "nacionalidade": "Brasileira",
                "naturalidade": "São Paulo",
                "rua": "Rua das Flores",
                "numero_imovel": "123",
                "complemento": "Apto 45",
                "bairro": "Jardim Primavera",
                "cidade": "São Paulo",
                "estado": "SP",
                "cep": "01234567",
                "nome_primeiro_contato": "Maria Silva",
                "celular_primeiro_contato": "11987654321",
                "tipo_relacionamento_primeiro_contato": "Mãe",
                "nome_segundo_contato": "Pedro Silva",
                "celular_segundo_contato": "11976543210",
                "tipo_relacionamento_segundo_contato": "Pai",
                "tipo_sanguineo": "A",
                "fator_rh": "+",
                "alergias": "Nenhuma",
                "condicoes_medicas_gerais": "Nenhuma",
                "convenio_medico": "Unimed",
                "hospital": "Hospital São Luiz",
            },
            {
                "cpf": "98765432109",
                "nome": "Maria Oliveira",
                "data_nascimento": date(1985, 10, 20),
                "hora_nascimento": time(14, 45),
                "email": "maria.oliveira@exemplo.com",
                "sexo": "F",
                "numero_iniciatico": "102B",
                "nome_iniciatico": "Shakti",
                "nacionalidade": "Brasileira",
                "naturalidade": "Rio de Janeiro",
                "rua": "Avenida Central",
                "numero_imovel": "456",
                "complemento": "Bloco C",
                "bairro": "Centro",
                "cidade": "Rio de Janeiro",
                "estado": "RJ",
                "cep": "20000123",
                "nome_primeiro_contato": "José Oliveira",
                "celular_primeiro_contato": "21987654321",
                "tipo_relacionamento_primeiro_contato": "Pai",
                "nome_segundo_contato": "Ana Oliveira",
                "celular_segundo_contato": "21976543210",
                "tipo_relacionamento_segundo_contato": "Mãe",
                "tipo_sanguineo": "O",
                "fator_rh": "-",
                "alergias": "Penicilina",
                "condicoes_medicas_gerais": "Asma leve",
                "convenio_medico": "Amil",
                "hospital": "Hospital Samaritano",
            },
            {
                "cpf": "45678912301",
                "nome": "Carlos Santos",
                "data_nascimento": date(1978, 3, 8),
                "hora_nascimento": time(10, 15),
                "email": "carlos.santos@exemplo.com",
                "sexo": "M",
                "numero_iniciatico": "103C",
                "nome_iniciatico": "Dharma",
                "nacionalidade": "Brasileira",
                "naturalidade": "Belo Horizonte",
                "rua": "Rua dos Ipês",
                "numero_imovel": "789",
                "complemento": "Casa",
                "bairro": "Savassi",
                "cidade": "Belo Horizonte",
                "estado": "MG",
                "cep": "30000456",
                "nome_primeiro_contato": "Lúcia Santos",
                "celular_primeiro_contato": "31987654321",
                "tipo_relacionamento_primeiro_contato": "Esposa",
                "nome_segundo_contato": "Roberto Santos",
                "celular_segundo_contato": "31976543210",
                "tipo_relacionamento_segundo_contato": "Irmão",
                "tipo_sanguineo": "B",
                "fator_rh": "+",
                "alergias": "Frutos do mar",
                "condicoes_medicas_gerais": "Hipertensão",
                "convenio_medico": "Bradesco Saúde",
                "hospital": "Hospital Mater Dei",
            },
            {
                "cpf": "78912345601",
                "nome": "Ana Souza",
                "data_nascimento": date(1995, 7, 25),
                "hora_nascimento": time(16, 30),
                "email": "ana.souza@exemplo.com",
                "sexo": "F",
                "numero_iniciatico": "104D",
                "nome_iniciatico": "Parvati",
                "nacionalidade": "Brasileira",
                "naturalidade": "Curitiba",
                "rua": "Rua das Araucárias",
                "numero_imovel": "321",
                "complemento": "Apto 12",
                "bairro": "Batel",
                "cidade": "Curitiba",
                "estado": "PR",
                "cep": "80000789",
                "nome_primeiro_contato": "Marcos Souza",
                "celular_primeiro_contato": "41987654321",
                "tipo_relacionamento_primeiro_contato": "Pai",
                "nome_segundo_contato": "Júlia Souza",
                "celular_segundo_contato": "41976543210",
                "tipo_relacionamento_segundo_contato": "Irmã",
                "tipo_sanguineo": "AB",
                "fator_rh": "+",
                "alergias": "Pólen",
                "condicoes_medicas_gerais": "Rinite alérgica",
                "convenio_medico": "Unimed",
                "hospital": "Hospital Nossa Senhora das Graças",
            },
            {
                "cpf": "32165498701",
                "nome": "Pedro Ferreira",
                "data_nascimento": date(1982, 12, 10),
                "hora_nascimento": time(22, 45),
                "email": "pedro.ferreira@exemplo.com",
                "sexo": "M",
                "numero_iniciatico": "105E",
                "nome_iniciatico": "Shiva",
                "nacionalidade": "Brasileira",
                "naturalidade": "Salvador",
                "rua": "Avenida do Mar",
                "numero_imovel": "654",
                "complemento": "Casa 3",
                "bairro": "Barra",
                "cidade": "Salvador",
                "estado": "BA",
                "cep": "40000123",
                "nome_primeiro_contato": "Carla Ferreira",
                "celular_primeiro_contato": "71987654321",
                "tipo_relacionamento_primeiro_contato": "Esposa",
                "nome_segundo_contato": "Antônio Ferreira",
                "celular_segundo_contato": "71976543210",
                "tipo_relacionamento_segundo_contato": "Pai",
                "tipo_sanguineo": "O",
                "fator_rh": "+",
                "alergias": "Nenhuma",
                "condicoes_medicas_gerais": "Nenhuma",
                "convenio_medico": "SulAmérica",
                "hospital": "Hospital Português",
            },
            {
                "cpf": "65432198701",
                "nome": "Juliana Costa",
                "data_nascimento": date(1988, 4, 18),
                "hora_nascimento": time(12, 20),
                "email": "juliana.costa@exemplo.com",
                "sexo": "F",
                "numero_iniciatico": "106F",
                "nome_iniciatico": "Lakshmi",
                "nacionalidade": "Brasileira",
                "naturalidade": "Recife",
                "rua": "Rua dos Navegantes",
                "numero_imovel": "987",
                "complemento": "Apto 56",
                "bairro": "Boa Viagem",
                "cidade": "Recife",
                "estado": "PE",
                "cep": "50000456",
                "nome_primeiro_contato": "Ricardo Costa",
                "celular_primeiro_contato": "81987654321",
                "tipo_relacionamento_primeiro_contato": "Marido",
                "nome_segundo_contato": "Fernanda Costa",
                "celular_segundo_contato": "81976543210",
                "tipo_relacionamento_segundo_contato": "Irmã",
                "tipo_sanguineo": "A",
                "fator_rh": "-",
                "alergias": "Amendoim",
                "condicoes_medicas_gerais": "Nenhuma",
                "convenio_medico": "Hapvida",
                "hospital": "Hospital Esperança",
            },
            {
                "cpf": "98701234567",
                "nome": "Lucas Almeida",
                "data_nascimento": date(1992, 9, 5),
                "hora_nascimento": time(7, 10),
                "email": "lucas.almeida@exemplo.com",
                "sexo": "M",
                "numero_iniciatico": "107G",
                "nome_iniciatico": "Krishna",
                "nacionalidade": "Brasileira",
                "naturalidade": "Brasília",
                "rua": "SQN 114",
                "numero_imovel": "Bloco A",
                "complemento": "Apto 303",
                "bairro": "Asa Norte",
                "cidade": "Brasília",
                "estado": "DF",
                "cep": "70000789",
                "nome_primeiro_contato": "Márcia Almeida",
                "celular_primeiro_contato": "61987654321",
                "tipo_relacionamento_primeiro_contato": "Mãe",
                "nome_segundo_contato": "Sérgio Almeida",
                "celular_segundo_contato": "61976543210",
                "tipo_relacionamento_segundo_contato": "Pai",
                "tipo_sanguineo": "B",
                "fator_rh": "-",
                "alergias": "Nenhuma",
                "condicoes_medicas_gerais": "Nenhuma",
                "convenio_medico": "Amil",
                "hospital": "Hospital Santa Lúcia",
            },
            {
                "cpf": "12378945601",
                "nome": "Fernanda Lima",
                "data_nascimento": date(1980, 2, 28),
                "hora_nascimento": time(18, 50),
                "email": "fernanda.lima@exemplo.com",
                "sexo": "F",
                "numero_iniciatico": "108H",
                "nome_iniciatico": "Saraswati",
                "nacionalidade": "Brasileira",
                "naturalidade": "Porto Alegre",
                "rua": "Rua Padre Chagas",
                "numero_imovel": "123",
                "complemento": "Casa",
                "bairro": "Moinhos de Vento",
                "cidade": "Porto Alegre",
                "estado": "RS",
                "cep": "90000123",
                "nome_primeiro_contato": "Gustavo Lima",
                "celular_primeiro_contato": "51987654321",
                "tipo_relacionamento_primeiro_contato": "Marido",
                "nome_segundo_contato": "Cláudia Lima",
                "celular_segundo_contato": "51976543210",
                "tipo_relacionamento_segundo_contato": "Mãe",
                "tipo_sanguineo": "AB",
                "fator_rh": "-",
                "alergias": "Látex",
                "condicoes_medicas_gerais": "Hipotireoidismo",
                "convenio_medico": "Unimed",
                "hospital": "Hospital Moinhos de Vento",
            },
            {
                "cpf": "45612378901",
                "nome": "Roberto Martins",
                "data_nascimento": date(1975, 11, 12),
                "hora_nascimento": time(5, 25),
                "email": "roberto.martins@exemplo.com",
                "sexo": "M",
                "numero_iniciatico": "109I",
                "nome_iniciatico": "Vishnu",
                "nacionalidade": "Brasileira",
                "naturalidade": "Fortaleza",
                "rua": "Avenida Beira Mar",
                "numero_imovel": "456",
                "complemento": "Apto 1001",
                "bairro": "Meireles",
                "cidade": "Fortaleza",
                "estado": "CE",
                "cep": "60000456",
                "nome_primeiro_contato": "Patrícia Martins",
                "celular_primeiro_contato": "85987654321",
                "tipo_relacionamento_primeiro_contato": "Esposa",
                "nome_segundo_contato": "Felipe Martins",
                "celular_segundo_contato": "85976543210",
                "tipo_relacionamento_segundo_contato": "Filho",
            },
        ]

        # Criar alunos no banco de dados
        for aluno_data in alunos_dados:
            try:
                # Verificar se o aluno já existe
                if not Aluno.objects.filter(cpf=aluno_data["cpf"]).exists():
                    aluno = Aluno.objects.create(**aluno_data)
                    self.stdout.write(
                        self.style.SUCCESS(f"Aluno {aluno.nome} criado com sucesso!")
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING(
                            f"Aluno com CPF {aluno_data['cpf']} já existe."
                        )
                    )
            except Exception as e:
                self.stdout.write(
                    self.style.ERROR(
                        f"Erro ao criar aluno {aluno_data['nome']}: {str(e)}"
                    )
                )

        self.stdout.write(self.style.SUCCESS("Comando executado com sucesso!"))
