# c:/omaum/presencas/urls_reports.py
from django.urls import path
from . import views_reports

urlpatterns = [
    # ===== CATEGORIA 5: RELATÓRIOS ADMINISTRATIVOS =====
    path(
        "dashboard-coordenacao/",
        views_reports.listar_dashboard_coordenacao,
        name="listar_dashboard_coordenacao",
    ),
    path(
        "ajax/dashboard-coordenacao/",
        views_reports.filtrar_dashboard_coordenacao,
        name="filtrar_dashboard_coordenacao",
    ),
    path(
        "dashboard-direcao/",
        views_reports.listar_dashboard_direcao,
        name="listar_dashboard_direcao",
    ),
    path(
        "ajax/dashboard-direcao/",
        views_reports.filtrar_dashboard_direcao,
        name="filtrar_dashboard_direcao",
    ),
    path(
        "metricas-professor/",
        views_reports.listar_metricas_professor,
        name="listar_metricas_professor",
    ),
    path(
        "ajax/metricas-professor/",
        views_reports.filtrar_metricas_professor,
        name="filtrar_metricas_professor",
    ),
    path(
        "indicadores-qualidade/",
        views_reports.listar_indicadores_qualidade,
        name="listar_indicadores_qualidade",
    ),
    # ===== CSV EXPORTS - CATEGORIA 5 =====
    path(
        "csv/dashboard-coordenacao/",
        views_reports.exportar_csv_dashboard_coordenacao,
        name="exportar_csv_dashboard_coordenacao",
    ),
    path(
        "csv/dashboard-direcao/",
        views_reports.exportar_csv_dashboard_direcao,
        name="exportar_csv_dashboard_direcao",
    ),
    path(
        "csv/metricas-professor/",
        views_reports.exportar_csv_metricas_professor,
        name="exportar_csv_metricas_professor",
    ),
    path(
        "csv/indicadores-qualidade/",
        views_reports.exportar_csv_indicadores_qualidade,
        name="exportar_csv_indicadores_qualidade",
    ),
    # ===== CATEGORIA 4: RELATÓRIOS PREDITIVOS (MACHINE LEARNING) =====
    path(
        "previsao-evasao/",
        views_reports.listar_previsao_evasao,
        name="listar_previsao_evasao",
    ),
    path(
        "ajax/previsao-evasao/",
        views_reports.filtrar_previsao_evasao,
        name="filtrar_previsao_evasao",
    ),
    path(
        "intervencoes-automaticas/",
        views_reports.listar_intervencoes_automaticas,
        name="listar_intervencoes_automaticas",
    ),
    path(
        "ajax/intervencoes-automaticas/",
        views_reports.filtrar_intervencoes_automaticas,
        name="filtrar_intervencoes_automaticas",
    ),
    path(
        "correlacao-presenca-desempenho/",
        views_reports.listar_correlacao_presenca_desempenho,
        name="listar_correlacao_presenca_desempenho",
    ),
    path(
        "ajax/correlacao-presenca-desempenho/",
        views_reports.filtrar_correlacao_presenca_desempenho,
        name="filtrar_correlacao_presenca_desempenho",
    ),
    # ===== CSV EXPORTS - CATEGORIA 4 =====
    path(
        "csv/previsao-evasao/",
        views_reports.exportar_csv_previsao_evasao,
        name="exportar_csv_previsao_evasao",
    ),
    path(
        "csv/intervencoes-automaticas/",
        views_reports.exportar_csv_intervencoes_automaticas,
        name="exportar_csv_intervencoes_automaticas",
    ),
    path(
        "csv/correlacao-presenca-desempenho/",
        views_reports.exportar_csv_correlacao_presenca_desempenho,
        name="exportar_csv_correlacao_presenca_desempenho",
    ),
    # ===== CATEGORIA 2: RELATÓRIOS DE CONSOLIDAÇÃO =====
    path(
        "boletim-frequencia-aluno/",
        views_reports.listar_boletim_frequencia_aluno,
        name="listar_boletim_frequencia_aluno",
    ),
    path(
        "ajax/boletim-frequencia-aluno/",
        views_reports.filtrar_boletim_frequencia_aluno,
        name="filtrar_boletim_frequencia_aluno",
    ),
    path(
        "consolidado-frequencia-turma/",
        views_reports.listar_consolidado_frequencia_turma,
        name="listar_consolidado_frequencia_turma",
    ),
    path(
        "ajax/consolidado-frequencia-turma/",
        views_reports.filtrar_consolidado_frequencia_turma,
        name="filtrar_consolidado_frequencia_turma",
    ),
    # ===== CATEGORIA 3: RELATÓRIOS ANALÍTICOS =====
    path(
        "alunos-em-risco/",
        views_reports.listar_alunos_em_risco,
        name="listar_alunos_em_risco",
    ),
    path(
        "ajax/alunos-em-risco/",
        views_reports.filtrar_alunos_em_risco,
        name="filtrar_alunos_em_risco",
    ),
    path(
        "ranking-engajamento/",
        views_reports.listar_ranking_engajamento,
        name="listar_ranking_engajamento",
    ),
    path(
        "ajax/ranking-engajamento/",
        views_reports.filtrar_ranking_engajamento,
        name="filtrar_ranking_engajamento",
    ),
    path(
        "comparativo-frequencia/",
        views_reports.listar_comparativo_frequencia,
        name="listar_comparativo_frequencia",
    ),
    path(
        "ajax/comparativo-frequencia/",
        views_reports.filtrar_comparativo_frequencia,
        name="filtrar_comparativo_frequencia",
    ),
    path(
        "dashboard/",
        views_reports.listar_dashboard_presencas,
        name="listar_dashboard_presencas",
    ),
    path(
        "ajax/dashboard/",
        views_reports.filtrar_dashboard_presencas,
        name="filtrar_dashboard_presencas",
    ),
    # ===== ENDPOINTS AJAX PARA FILTROS DINÂMICOS =====
    path(
        "ajax/turmas/",
        views_reports.ajax_turmas,
        name="ajax_turmas",
    ),
    path(
        "ajax/anos/",
        views_reports.ajax_anos,
        name="ajax_anos",
    ),
    path(
        "ajax/alunos/",
        views_reports.ajax_alunos,
        name="ajax_alunos",
    ),
]
