# Generated by Django 5.1.7 on 2025-05-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('cursos', '0001_initial'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAcademica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                (
                    'descricao',
                    models.TextField(blank=True, null=True, verbose_name='Descrição'),
                ),
                (
                    'tipo_atividade',
                    models.CharField(
                        choices=[
                            ('AULA', 'Aula'),
                            ('PROVA', 'Prova'),
                            ('SEMINARIO', 'Seminário'),
                            ('OUTRO', 'Outro'),
                        ],
                        max_length=20,
                        verbose_name='Tipo de Atividade',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDENTE', 'Pendente'),
                            ('REALIZADA', 'Realizada'),
                            ('CANCELADA', 'Cancelada'),
                        ],
                        default='PENDENTE',
                        max_length=20,
                        verbose_name='Status',
                    ),
                ),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                (
                    'data_fim',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Data de Fim'
                    ),
                ),
                (
                    'responsavel',
                    models.CharField(max_length=100, verbose_name='Responsável'),
                ),
                (
                    'local',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='Local'
                    ),
                ),
                (
                    'curso',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='atividades_academicas',
                        to='cursos.curso',
                        verbose_name='Curso',
                    ),
                ),
                (
                    'turmas',
                    models.ManyToManyField(
                        blank=True,
                        related_name='atividades_academicas',
                        to='turmas.turma',
                        verbose_name='Turmas',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Atividade Acadêmica',
                'verbose_name_plural': 'Atividades Acadêmicas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeRitualistica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                (
                    'descricao',
                    models.TextField(blank=True, null=True, verbose_name='Descrição'),
                ),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                (
                    'participantes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='atividades_ritualisticas',
                        to='alunos.aluno',
                        verbose_name='Participantes',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Atividade Ritualística',
                'verbose_name_plural': 'Atividades Ritualísticas',
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
    ]
