# Generated by Django 5.2.9 on 2025-12-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('AULA', 'Aula'), ('PLENILUNIO', 'Plenilúnio'), ('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop'), ('SEMINARIO', 'Seminário'), ('OUTRO', 'Outro')], default='AULA', max_length=20),
        ),
    ]
