# Generated by Django 5.1.7 on 2025-05-27 02:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('atividades', '0001_initial'),
        ('cursos', '0001_initial'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeacademica',
            options={
                'ordering': ['-data_inicio', 'hora_inicio'],
                'verbose_name': 'Atividade Acadêmica',
                'verbose_name_plural': 'Atividades Acadêmicas',
            },
        ),
        migrations.RemoveField(
            model_name='atividaderitualistica',
            name='turma',
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 27, 2, 20, 54, 3142, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 27, 2, 22, 14, 815854, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('CONFIRMADA', 'Confirmada'),
                    ('REALIZADA', 'Realizada'),
                    ('CANCELADA', 'Cancelada'),
                ],
                default='PENDENTE',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='curso',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='atividades',
                to='cursos.curso',
            ),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDENTE', 'Pendente'),
                    ('CONFIRMADA', 'Confirmada'),
                    ('REALIZADA', 'Realizada'),
                    ('CANCELADA', 'Cancelada'),
                ],
                default='PENDENTE',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='tipo_atividade',
            field=models.CharField(
                choices=[
                    ('AULA', 'Aula'),
                    ('PALESTRA', 'Palestra'),
                    ('WORKSHOP', 'Workshop'),
                    ('SEMINARIO', 'Seminário'),
                    ('OUTRO', 'Outro'),
                ],
                default='AULA',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='turmas',
            field=models.ManyToManyField(
                blank=True, related_name='atividades', to='turmas.turma'
            ),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='participantes',
            field=models.ManyToManyField(
                blank=True, related_name='atividades_ritualisticas', to='alunos.aluno'
            ),
        ),
    ]
