# Generated by Django 5.2.2 on 2025-06-14 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('atividades', '0002_alter_atividadeacademica_options_and_more'),
        ('turmas', '0009_alter_turma_options_remove_turma_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeacademica',
            name='convocacao',
            field=models.BooleanField(default=False, verbose_name='Convocação'),
        ),
        migrations.AddField(
            model_name='atividadeacademica',
            name='tipo',
            field=models.CharField(
                choices=[('academica', 'Acadêmica'), ('ritualistica', 'Ritualística')],
                default='academica',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='convocacao',
            field=models.BooleanField(default=False, verbose_name='Convocação'),
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='tipo',
            field=models.CharField(
                choices=[('academica', 'Acadêmica'), ('ritualistica', 'Ritualística')],
                default='academica',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='ObservacaoPresenca',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField(verbose_name='Data')),
                (
                    'texto',
                    models.TextField(blank=True, null=True, verbose_name='Observação'),
                ),
                (
                    'registrado_por',
                    models.CharField(
                        default='Sistema', max_length=100, verbose_name='Registrado por'
                    ),
                ),
                (
                    'data_registro',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Data de registro',
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='alunos.aluno',
                        verbose_name='Aluno',
                    ),
                ),
                (
                    'atividade_academica',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='atividades.atividadeacademica',
                        verbose_name='Atividade Acadêmica',
                    ),
                ),
                (
                    'atividade_ritualistica',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='atividades.atividaderitualistica',
                        verbose_name='Atividade Ritualística',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Observação de Presença',
                'verbose_name_plural': 'Observações de Presença',
                'ordering': ['-data', 'aluno__nome'],
            },
        ),
        migrations.CreateModel(
            name='PresencaAcademica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField(verbose_name='Data')),
                (
                    'presente',
                    models.BooleanField(default=True, verbose_name='Presente'),
                ),
                (
                    'registrado_por',
                    models.CharField(
                        default='Sistema', max_length=100, verbose_name='Registrado por'
                    ),
                ),
                (
                    'data_registro',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Data de registro',
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='alunos.aluno',
                        verbose_name='Aluno',
                    ),
                ),
                (
                    'atividade',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='atividades.atividadeacademica',
                        verbose_name='Atividade Acadêmica',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Presença Acadêmica',
                'verbose_name_plural': 'Presenças Acadêmicas',
                'ordering': ['-data', 'aluno__nome'],
                'abstract': False,
                'unique_together': {('aluno', 'turma', 'atividade', 'data')},
            },
        ),
        migrations.CreateModel(
            name='PresencaRitualistica',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField(verbose_name='Data')),
                (
                    'presente',
                    models.BooleanField(default=True, verbose_name='Presente'),
                ),
                (
                    'registrado_por',
                    models.CharField(
                        default='Sistema', max_length=100, verbose_name='Registrado por'
                    ),
                ),
                (
                    'data_registro',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Data de registro',
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='alunos.aluno',
                        verbose_name='Aluno',
                    ),
                ),
                (
                    'atividade',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='atividades.atividaderitualistica',
                        verbose_name='Atividade Ritualística',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Presença Ritualística',
                'verbose_name_plural': 'Presenças Ritualísticas',
                'ordering': ['-data', 'aluno__nome'],
                'abstract': False,
                'unique_together': {('aluno', 'turma', 'atividade', 'data')},
            },
        ),
    ]
