# Generated by Django 5.1.7 on 2025-04-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_initial'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeacademica',
            name='turmas',
            field=models.ManyToManyField(
                related_name='atividades_academicas',
                to='turmas.turma',
                verbose_name='Turmas',
            ),
        ),
        migrations.AlterField(
            model_name='atividadeacademica',
            name='turma',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='atividades_academicas_legacy',
                to='turmas.turma',
            ),
        ),
    ]
