# Generated by Django 5.2.2 on 2025-06-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividadeacademica_convocacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObservacaoPresenca',
        ),
    ]
