# Generated by Django 5.1.7 on 2025-05-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_populate_turmas_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeacademica',
            name='turma',
        ),
    ]
