# Generated by Django 5.1.7 on 2025-04-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_id_alter_aluno_cpf'),
        ('atividades', '0002_initial'),
        ('turmas', '0002_alter_matricula_options_remove_matricula_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividaderitualistica',
            options={'ordering': ['-data', 'hora_inicio'], 'verbose_name': 'Atividade Ritualística', 'verbose_name_plural': 'Atividades Ritualísticas'},
        ),
        migrations.RemoveField(
            model_name='atividaderitualistica',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='atividaderitualistica',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atividaderitualistica',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='data',
            field=models.DateField(default='2023-01-01', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='hora_fim',
            field=models.TimeField(default='12:00', verbose_name='Hora de Término'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='hora_inicio',
            field=models.TimeField(default='10:00', verbose_name='Hora de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='local',
            field=models.CharField(default=1, max_length=100, verbose_name='Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividaderitualistica',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='atividades_ritualisticas', to='alunos.aluno', verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='atividaderitualistica',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma', verbose_name='Turma'),
        ),
    ]
