# Generated by Django 5.1.7 on 2025-04-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_atividaderitualistica_options_and_more'),
        ('atividades', 'XXXX_add_titulo_column'),
    ]

    operations = [
    ]
