"""
Django settings for omaum project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
print(f"ARQUIVO VIEWS.PY CARREGADO: {os.path.abspath(__file__)}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Adjust this path to where gettext is actually installed
GETTEXT_PATH = r'C:\msys64\usr\bin'
os.environ['PATH'] += os.pathsep + GETTEXT_PATH

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1odw#x&ng-if-cpk9zupxzv&)y7sqxe&-(g3isa6l!l6oh(ht%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # Certifique-se de que esta linha está presente
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Your custom apps
    'alunos',
    'atividades',
    'cargos',
    'core',
    'cursos',
    'frequencias',
    'iniciacoes',
    'presencas',
    'punicoes',
    'relatorios',
    'turmas',
    # Other apps as needed
]

MIDDLEWARE = [
    'core.middleware.manutencao_middleware',
    'core.middleware.renovacao_sessao_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    INTERNAL_IPS = ['127.0.0.1']

CRISPY_TEMPLATE_PACK = 'bootstrap4'

ROOT_URLCONF = 'omaum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'omaum', 'templates'),  # Caminho correto para os templates do projeto
            os.path.join(BASE_DIR, 'templates'),  # Manter o caminho original como fallback
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omaum.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'pt-BR'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'core:entrar'  # Alterado para usar a view de login do core

# Specifies the directory paths for localization (translation) files in the Django project
LOCALE_PATHS = (
    BASE_DIR / 'locale',
)

# Configurações de sessão e CSRF atualizadas
SESSION_COOKIE_AGE = 86400 * 7  # Aumentar para 7 dias (em segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Salvar a sessão a cada requisição
CSRF_COOKIE_AGE = 86400 * 7  # Aumentar para 7 dias
CSRF_USE_SESSIONS = True  # Armazenar o token CSRF na sessão para maior segurança
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Não expirar a sessão ao fechar o navegador

# Configurações para renovação de sessão
SESSION_SECURITY_WARN_AFTER = 3000  # Avisar após 50 minutos de inatividade
SESSION_SECURITY_EXPIRE_AFTER = 3600  # Expirar após 60 minutos de inatividade
