# Generated by Django 5.2.2 on 2025-09-13 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_alter_aluno_celular_primeiro_contato_and_more"),
        ("atividades", "0001_initial"),
        ("presencas", "0001_initial"),
        ("turmas", "0002_remove_turma_perc_carencia_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="configuracaopresenca",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="configuracaopresenca",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="configuracaopresenca",
            name="turma",
        ),
        migrations.AlterUniqueTogether(
            name="convocacaopresenca",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="convocacaopresenca",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="convocacaopresenca",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="convocacaopresenca",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="observacaopresenca",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="observacaopresenca",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="observacaopresenca",
            name="turma",
        ),
        migrations.AlterUniqueTogether(
            name="presenca",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="presenca",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="presenca",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="presenca",
            name="turma",
        ),
        migrations.AlterUniqueTogether(
            name="presencadetalhada",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="presencadetalhada",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="presencadetalhada",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="presencadetalhada",
            name="turma",
        ),
        migrations.AlterUniqueTogether(
            name="totalatividademes",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="totalatividademes",
            name="atividade",
        ),
        migrations.RemoveField(
            model_name="totalatividademes",
            name="turma",
        ),
        migrations.CreateModel(
            name="RegistroPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Presente"),
                            ("F", "Falta"),
                            ("J", "Falta Justificada"),
                            ("V1", "Voluntário Extra"),
                            ("V2", "Voluntário Simples"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("justificativa", models.TextField(blank=True, null=True)),
                ("convocado", models.BooleanField(default=True)),
                ("registrado_por", models.CharField(default="Sistema", max_length=100)),
                (
                    "data_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_de_presenca",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_de_presenca",
                        to="atividades.atividade",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_de_presenca",
                        to="turmas.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Presença",
                "verbose_name_plural": "Registros de Presença",
                "ordering": ["-data", "aluno__nome"],
                "unique_together": {("aluno", "turma", "atividade", "data")},
            },
        ),
        migrations.DeleteModel(
            name="AgendamentoRelatorio",
        ),
        migrations.DeleteModel(
            name="ConfiguracaoPresenca",
        ),
        migrations.DeleteModel(
            name="ConvocacaoPresenca",
        ),
        migrations.DeleteModel(
            name="ObservacaoPresenca",
        ),
        migrations.DeleteModel(
            name="Presenca",
        ),
        migrations.DeleteModel(
            name="PresencaDetalhada",
        ),
        migrations.DeleteModel(
            name="TotalAtividadeMes",
        ),
    ]
