# Generated by Django 5.1.7 on 2025-05-06 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('atividades', '0005_remove_atividadeacademica_turma'),
        ('presencas', '0002_presenca_delete_presencaacademica'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={
                'ordering': ['-data', 'aluno__nome'],
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
            },
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='status',
        ),
        migrations.AddField(
            model_name='presenca',
            name='atividade',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='atividades.atividadeacademica',
                verbose_name='Atividade',
            ),
        ),
        migrations.AddField(
            model_name='presenca',
            name='data_registro',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Data de registro'
            ),
        ),
        migrations.AddField(
            model_name='presenca',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='presente',
            field=models.BooleanField(default=True, verbose_name='Presente'),
        ),
        migrations.AddField(
            model_name='presenca',
            name='registrado_por',
            field=models.CharField(
                default='Sistema', max_length=100, verbose_name='Registrado por'
            ),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='alunos.aluno',
                verbose_name='Aluno',
            ),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='turma',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='turmas.turma',
                verbose_name='Turma',
            ),
        ),
    ]
