# Generated by Django 5.1.7 on 2025-05-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('presencas', '0003_alter_presenca_options_remove_presenca_status_and_more'),
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('aluno', 'turma', 'data')},
        ),
    ]
