# Generated by Django 5.2.5 on 2025-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presencas", "0003_create_presencadetalhada_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Presença (legado)",
                "verbose_name_plural": "Configurações de Presença (legado)",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PresencaDetalhada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.DateField()),
                ("convocacoes", models.PositiveIntegerField(default=0)),
                ("presencas", models.PositiveIntegerField(default=0)),
                ("faltas", models.PositiveIntegerField(default=0)),
                ("voluntario_extra", models.PositiveIntegerField(default=0)),
                ("voluntario_simples", models.PositiveIntegerField(default=0)),
                ("carencias", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Presença Detalhada (legado)",
                "verbose_name_plural": "Presenças Detalhadas (legado)",
                "db_table": "presencas_presencadetalhada",
                "ordering": ["-periodo", "aluno__nome"],
                "managed": False,
            },
        ),
    ]
