# Generated by Django 5.2.9 on 2025-12-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_update_foto_upload_path'),
        ('atividades', '0002_alter_atividade_tipo_atividade'),
        ('presencas', '0004_configuracaopresenca_presencadetalhada'),
        ('turmas', '0006_alter_turma_dias_semana'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['data'], name='rp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['status', 'data'], name='rp_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['turma', 'data'], name='rp_turma_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['atividade', 'data'], name='rp_atividade_data_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresenca',
            index=models.Index(fields=['aluno', 'data'], name='rp_aluno_data_idx'),
        ),
    ]
