# Generated by Django 5.2.2 on 2025-06-16 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividadeacademica_convocacao_and_more'),
        ('presencas', '0004_alter_presenca_unique_together'),
        ('turmas', '0009_alter_turma_options_remove_turma_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAtividadeMes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('qtd_ativ_mes', models.PositiveIntegerField(default=0)),
                ('registrado_por', models.CharField(default='Sistema', max_length=100)),
                (
                    'data_registro',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'atividade',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='atividades.atividadeacademica',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Total de Atividade no Mês',
                'verbose_name_plural': 'Totais de Atividades no Mês',
                'unique_together': {('atividade', 'turma', 'ano', 'mes')},
            },
        ),
    ]
