# Generated by Django 5.2.2 on 2025-06-17 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_situacao'),
        ('atividades', '0004_delete_observacaopresenca'),
        ('presencas', '0005_totalatividademes'),
        ('turmas', '0009_alter_turma_options_remove_turma_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoPresenca',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField(verbose_name='Data')),
                (
                    'texto',
                    models.TextField(blank=True, null=True, verbose_name='Observação'),
                ),
                (
                    'registrado_por',
                    models.CharField(
                        default='Sistema', max_length=100, verbose_name='Registrado por'
                    ),
                ),
                (
                    'data_registro',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Data de registro',
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observacoes_presenca_presencas',
                        to='alunos.aluno',
                        verbose_name='Aluno',
                    ),
                ),
                (
                    'atividade_academica',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observacoes_presenca_presencas',
                        to='atividades.atividadeacademica',
                        verbose_name='Atividade Acadêmica',
                    ),
                ),
                (
                    'atividade_ritualistica',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observacoes_presenca_presencas',
                        to='atividades.atividaderitualistica',
                        verbose_name='Atividade Ritualística',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observacoes_presenca_presencas',
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Observação de Presença',
                'verbose_name_plural': 'Observações de Presença',
                'ordering': ['-data'],
            },
        ),
    ]
