# Generated by Django 5.2.2 on 2025-08-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0009_database_indexes_optimization'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='presencadetalhada',
            name='pd_aluno_periodo',
        ),
        migrations.RemoveIndex(
            model_name='presencadetalhada',
            name='pd_turma_periodo',
        ),
        migrations.RemoveIndex(
            model_name='presencadetalhada',
            name='pd_ativ_periodo',
        ),
        migrations.RemoveIndex(
            model_name='presencadetalhada',
            name='pd_aln_ativ_per',
        ),
    ]
