# Generated by Django 5.2.2 on 2025-07-11 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data_matricula', models.DateField(verbose_name='Data da Matrícula')),
                (
                    'ativa',
                    models.BooleanField(default=True, verbose_name='Matrícula Ativa'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('A', 'Ativa'),
                            ('C', 'Cancelada'),
                            ('F', 'Finalizada'),
                        ],
                        default='A',
                        max_length=1,
                        verbose_name='Status',
                    ),
                ),
                (
                    'aluno',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='alunos.aluno',
                        verbose_name='Aluno',
                    ),
                ),
                (
                    'turma',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='matriculas',
                        to='turmas.turma',
                        verbose_name='Turma',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-data_matricula'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
