# Generated by Django 5.2.9 on 2025-12-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='ativa',
        ),
    ]
