# Generated by Django 5.2.2 on 2025-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turma",
            name="perc_carencia",
        ),
        migrations.AddField(
            model_name="turma",
            name="perc_presenca_minima",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual mínimo de presenças permitido para a turma",
                max_digits=5,
                null=True,
                verbose_name="Percentual Mínimo de Presença (%)",
            ),
        ),
    ]
