# Generated by Django 5.1.7 on 2025-04-12 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("turmas", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Matricula",
        ),
    ]
