# Generated by Django 5.1.7 on 2025-04-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
        ("turmas", "0002_delete_matricula"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="turma",
            options={
                "ordering": ["-data_inicio"],
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together={("data_inicio", "curso"), ("nome", "curso")},
        ),
        migrations.AddField(
            model_name="turma",
            name="vagas",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Capacidade"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Término"),
        ),
        migrations.AlterField(
            model_name="turma",
            name="descricao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="nome",
            field=models.CharField(
                max_length=100, verbose_name="Nome da Turma"
            ),
        ),
        migrations.RemoveField(
            model_name="turma",
            name="capacidade",
        ),
    ]
