# Generated by Django 5.2.5 on 2025-12-05 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("turmas", "0003_turma_data_fim_turma_data_inicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turma",
            name="data_fim",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="data_inicio",
        ),
    ]
