# Generated by Django 5.1.7 on 2025-04-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_aluno_situacao"),
        (
            "turmas",
            "0003_alter_turma_options_alter_turma_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="turma",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="turma",
            name="alerta_instrutor",
            field=models.BooleanField(
                default=False, verbose_name="Alerta de Instrutor"
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="alerta_mensagem",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mensagem de Alerta"
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="auxiliar_instrucao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas_como_auxiliar_instrucao",
                to="alunos.aluno",
                verbose_name="Auxiliar de Instrução",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="instrutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas_como_instrutor",
                to="alunos.aluno",
                verbose_name="Instrutor",
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="instrutor_auxiliar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turmas_como_instrutor_auxiliar",
                to="alunos.aluno",
                verbose_name="Instrutor Auxiliar",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="vagas",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Número de Vagas"
            ),
        ),
    ]
