# Generated by Django 5.1.7 on 2025-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turmas", "0005_remove_turma_alerta_instrutor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="alerta_instrutor",
            field=models.BooleanField(
                default=False, verbose_name="Alerta de Instrutor"
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="alerta_mensagem",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mensagem de Alerta"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="data_fim",
            field=models.DateField(verbose_name="Data de Fim"),
        ),
    ]
