# Generated by Django 5.1.7 on 2025-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_turma_alerta_instrutor_turma_alerta_mensagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(
                choices=[
                    ('A', 'Ativa'),
                    ('I', 'Inativa'),
                    ('C', 'Cancelada'),
                    ('F', 'Finalizada'),
                ],
                default='A',
                max_length=1,
                verbose_name='Status',
            ),
        ),
    ]
