# Generated by Django 5.2.2 on 2025-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_alter_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='data_iniciacao',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data de Iniciação'
            ),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_inicio_ativ',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data de Início das Atividades'
            ),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_prim_aula',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data da Primeira Aula'
            ),
        ),
        migrations.AddField(
            model_name='turma',
            name='num_livro',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Nº do Livro de Presenças'
            ),
        ),
        migrations.AddField(
            model_name='turma',
            name='perc_carencia',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Percentual mínimo de faltas permitido para a turma.',
                max_digits=5,
                null=True,
                verbose_name='Percentual de Carência (%)',
            ),
        ),
    ]
