# Generated by Django 5.2.2 on 2025-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_turma_data_iniciacao_turma_data_inicio_ativ_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={
                'ordering': ['-data_inicio_ativ'],
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.RemoveField(
            model_name='turma',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='turma',
            name='data_termino_atividades',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data de Término das Atividades'
            ),
        ),
    ]
