# Generated by Django 5.1.7 on 2025-04-02 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0002_remove_aluno_id_alter_aluno_cpf"),
        ("punicoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="punicao",
            options={
                "ordering": ["-data_aplicacao", "aluno__nome"],
                "verbose_name": "Punição",
                "verbose_name_plural": "Punições",
            },
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="data_registro",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="data_termino",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="registrado_por",
        ),
        migrations.RemoveField(
            model_name="punicao",
            name="status",
        ),
        migrations.RemoveField(
            model_name="tipopunicao",
            name="gravidade",
        ),
        migrations.AddField(
            model_name="punicao",
            name="aplicada_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aplicada por",
            ),
        ),
        migrations.AddField(
            model_name="punicao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Criado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="punicao",
            name="motivo",
            field=models.TextField(default=1, verbose_name="Motivo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="punicao",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="punicao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alunos.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.AlterField(
            model_name="punicao",
            name="data_aplicacao",
            field=models.DateField(verbose_name="Data de Aplicação"),
        ),
        migrations.AlterField(
            model_name="punicao",
            name="observacoes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="punicao",
            name="tipo_punicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="punicoes.tipopunicao",
                verbose_name="Tipo de Punição",
            ),
        ),
        migrations.AlterField(
            model_name="tipopunicao",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="tipopunicao",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
